SELECT COUNT(INFO.FISH_TYPE) AS FISH_COUNT, NAME.FISH_NAME
FROM FISH_INFO INFO
JOIN FISH_NAME_INFO NAME ON NAME.FISH_TYPE = INFO.FISH_TYPE 
GROUP BY INFO.FISH_TYPE, NAME.FISH_NAME
ORDER BY COUNT(FISH_TYPE) DESC;